# Generated by Django 4.1.4 on 2022-12-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("O", "Oil Change"),
                            ("C", "Car Wash"),
                            ("R", "Repair"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "Car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.car"
                    ),
                ),
            ],
        ),
    ]
