# Generated by Django 4.1.4 on 2022-12-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="Car",
            new_name="car",
        ),
    ]
