# Generated by Django 4.1.4 on 2022-12-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_rename_car_service_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="date",
            field=models.DateField(verbose_name="feeding date"),
        ),
    ]
