# Generated by Django 4.1.4 on 2022-12-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_maintenance_delete_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=250)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="maintenance",
            options={"ordering": ["-date"]},
        ),
    ]
