# Generated by Django 4.1.4 on 2022-12-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_accessory_alter_maintenance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="accessories",
            field=models.ManyToManyField(to="main_app.accessory"),
        ),
    ]
